wordpress_sites:
  spacestation:
    site_hosts:
      - example.com
    local_path: ../spacestation # path targeting local Spacestation site directory (relative to Ansible root)
    repo: git@github.com:example/example.com.git # replace with your Git repo URL
    branch: master
    repo_subtree_path: spacestation # relative path to your Spacestation/WP directory in your repo
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
      duration: 30s
    env:
      wp_home: http://example.com
      wp_siteurl: http://example.com/wp
      db_name: example_prod
      db_user: example_dbuser
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
