composer_keep_updated: true
composer_global_packages:
 - { name: hirak/prestissimo }
apt_cache_valid_time: 86400
default_timezone: Etc/UTC
www_root: /srv/www
ip_whitelist:
  - "{{ lookup('pipe', 'curl -4 -s https://api.ipify.org') }}"

wordpress_env_defaults:
  wp_env: "{{ env }}"
  disable_wp_cron: true
